export const TYPES=['PTO','1/2 Day PTO','Non-PTO / Out','Called Out','Sick Leave','Vacation','Other'];
export const PUBLIC_TYPES=['PTO','Non-PTO / Out','1/2 Day PTO'];
export function clean(v,n=500){return String(v??'').trim().slice(0,n)}
export function validDate(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const date=new Date(v+'T00:00:00Z');return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===v}
export function validMonth(v){return typeof v==='string'&&/^\d{4}-(0[1-9]|1[0-2])$/.test(v)}
export function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
export function earliestAdvanceDate(now=new Date()){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const part=type=>Number(parts.find(value=>value.type===type).value);const date=new Date(Date.UTC(part('year'),part('month')-1,part('day')+2));return date.toISOString().slice(0,10)}
export function expandSubmissionDates(x){const mode=clean(x.date_mode,20)||'single';let dates=[];if(mode==='single')dates=[clean(x.event_date,10)];else if(mode==='multiple')dates=(Array.isArray(x.selected_dates)?x.selected_dates:[]).map(date=>clean(date,10));else if(mode==='range'){const start=clean(x.range_start,10),end=clean(x.range_end,10);if(!validDate(start)||!validDate(end)||start>end)return'Choose a valid start and end date.';const cursor=new Date(start+'T00:00:00Z'),last=new Date(end+'T00:00:00Z');while(cursor<=last&&dates.length<=93){dates.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1)}}else return'Choose a valid date selection option.';dates=[...new Set(dates.filter(Boolean))].sort();if(!dates.length||dates.some(date=>!validDate(date)))return'Choose all requested dates.';if(dates.length>93)return'A request can include no more than 93 dates.';return dates}
export function validatePublicSubmission(x){if(!x||typeof x!=='object'||Array.isArray(x))return'Enter valid request details.';const name=clean(x.name,120),email=clean(x.email,180).toLowerCase(),request_type=clean(x.request_type,40),reason=clean(x.reason,1000),dates=expandSubmissionDates(x);if(!name)return'Enter the employee name.';if(!validEmail(email))return'Enter a valid employee email.';if(!PUBLIC_TYPES.includes(request_type))return'Choose PTO, 1/2 Day PTO, or Non-PTO / Out.';if(typeof dates==='string')return dates;if((request_type==='PTO'||request_type==='1/2 Day PTO')&&dates.some(date=>date<earliestAdvanceDate()))return'PTO dates must be at least two calendar days after today.';if(request_type==='Non-PTO / Out'&&!reason)return'Enter a reason for Non-PTO / Out.';return{submitter_type:'Employee',name,email,request_type,reason,dates}}
export function validateEntry(x,{enforceAdvance=false,allowParent=false}={}){if(!x||typeof x!=='object'||Array.isArray(x))return'Enter valid request details.';const submitter_type=clean(x.submitter_type,20),name=clean(x.name,120),email=clean(x.email,180).toLowerCase(),request_type=clean(x.request_type,40),event_date=clean(x.event_date,10),reason=clean(x.reason,1000);if(submitter_type!=='Employee'&&!(allowParent&&submitter_type==='Parent'))return'Only employee records are supported.';if(!name)return'Enter the employee name.';if(email&&!validEmail(email))return'Enter a valid employee email.';if(!TYPES.includes(request_type))return'Choose a valid request type.';if(!validDate(event_date))return'Choose a valid date.';if(enforceAdvance&&(request_type==='PTO'||request_type==='1/2 Day PTO')&&event_date<earliestAdvanceDate())return'PTO and 1/2 Day PTO dates must be at least two calendar days after today.';if(request_type==='Non-PTO / Out'&&!reason)return'Enter a reason for Non-PTO / Out.';return{submitter_type,name,email,request_type,event_date,reason}}
